In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/zheyue/Workspace/Projects/cs-e4780/2014-citibike-tripdata/2_February/201402-citibike-tripdata_1.csv')

In [4]:
df = pd.read_csv("/Users/zheyue/Workspace/Projects/cs-e4780/OpenCEP/scripts/demo_data.csv")

In [5]:
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,382,2014-01-31 23:57:00,2014-02-01 00:02:22,24,Washington Square E,40.730494,-73.995721,28,Stanton St & Chrystie St,40.722293,-73.991475,21101,Subscriber,1991,1
1,382,2014-02-01 00:05:00,2014-02-01 00:06:22,28,Washington Square E,40.730494,-73.995721,294,Stanton St & Chrystie St,40.722293,-73.991475,21101,Subscriber,1991,1
2,382,2014-02-01 00:06:23,2014-02-01 00:07:25,294,Washington Square E,40.730494,-73.995721,265,Stanton St & Chrystie St,40.722293,-73.991475,21101,Subscriber,1991,1

In [5]:
df.iloc[:1].to_csv('/Users/zheyue/Workspace/Projects/cs-e4780/2014-citibike-tripdata/2_February/201402-citibike-tripdata_2.csv', index=False)

In [6]:
df.iloc[:1]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,382,2014-02-01 00:00:00,2014-02-01 00:06:22,294,Washington Square E,40.730494,-73.995721,265,Stanton St & Chrystie St,40.722293,-73.991475,21101,Subscriber,1991,1